"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
continuation_prompt = "[▸▹ ](dimmed white)"

format = """$cmd_duration\
$hostname\
$localip\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$container\
$docker_context\
$package\
$c\
$cpp\
$cmake\
$deno\
$dotnet\
$golang\
$java\
$gradle\
$nodejs\
$python\
$rust\
$status"""

[character]
format = "$symbol "
success_symbol = "[›](bold cyan)"
error_symbol = "[›](bold red)"
vimcmd_symbol = "[■](italic dimmed green)"
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "bold italic red"
symbol = " "
disabled = false

[username]
style_user = "cyan bold italic"
style_root = "red bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = "⌂"
truncation_length = 2
truncation_symbol = "□ "
read_only = " ◈"
use_os_path_sep = true
style = "italic cyan"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold cyan'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [△](bold cyan)'

[cmd_duration]
format = "[◄ $duration ](italic white)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[▶](cyan italic)"

[localip]
ssh_only = true
format = " [ssh $localipv4](bold red)"
disabled = false

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = "[△](bold italic cyan)"
style = "italic cyan"
truncation_symbol = "⋯"
truncation_length = 11
ignore_branches = ["main", "master"]
only_attached = true

[git_status]
style = "bold italic cyan"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[◪◦](italic red)"
ahead = "[▴│[${count}](bold white)│](italic green)"
behind = "[▿│[${count}](bold white)│](italic red)"
diverged = "[◇ ▴┤[${ahead_count}](regular white)│▿┤[${behind_count}](regular white)│](italic red)"
untracked = "[◌◦](italic cyan)"
stashed = "[◃◈](italic white)"
modified = "[●◦](italic cyan)"
staged = "[▪┤[$count](bold white)│](italic cyan)"
renamed = "[◎◦](italic cyan)"
deleted = "[✕](italic red)"

[deno]
format = " [deno](italic) [∫ $version](green bold)"
version_format = "${raw}"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "⨀ "
style = "bold cyan"

[nodejs]
format = " [node](italic) [◫ ($version)](bold green)"
version_format = "${raw}"
detect_files = ["package.json", "package-lock.json", "pnpm-lock.yaml", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts"]

[python]
format = " [py](italic) [${symbol}${version}]($style)"
symbol = "[⌉](bold cyan)⌊ "
version_format = "${raw}"
style = "bold cyan"

[rust]
format = " [rs](italic) [$symbol$version]($style)"
symbol = "⊃ "
version_format = "${raw}"
style = "bold red"

[package]
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "◨ "
style = "dimmed cyan italic bold"

[c]
symbol = "ℂ "
format = " [$symbol($version(-$name))]($style)"

[cpp]
symbol = "ℂ "
format = " [$symbol($version(-$name))]($style)"

[docker_context]
symbol = "◧ "
format = " docker [$symbol$context]($style)"

[golang]
symbol = "∩ "
format = " go [$symbol($version )]($style)"

[java]
symbol = "∪ "
format = " java [${symbol}(${version} )]($style)"
