include ~/.config/sway/outputs
include ~/.config/sway/workspaces
include ~/.config/dotfiles/hardware.d/sway.conf

exec_always --no-startup-id ~/.local/bin/dotfiles-waybar
exec --no-startup-id mako
exec --no-startup-id swayidle -C ~/.config/swayidle/config
exec --no-startup-id playerctld daemon
exec --no-startup-id blueman-applet
exec --no-startup-id /usr/libexec/polkit-mate-authentication-agent-1
exec --no-startup-id wl-paste --type text --watch cliphist store
exec --no-startup-id wl-paste --type image --watch cliphist store
exec --no-startup-id ~/.local/bin/dotfiles-microphone sync
exec --no-startup-id ~/.local/bin/dotfiles-wlsunset
