exec_always --no-startup-id ~/.local/bin/dotfiles-waybar
exec --no-startup-id mako
exec --no-startup-id swayidle -C ~/.config/swayidle/config
exec --no-startup-id wl-paste --type text --watch cliphist store
exec --no-startup-id wl-paste --type image --watch cliphist store
