unbindsym Print
bindsym Print exec ~/.local/bin/dotfiles-screenshot full
bindsym $mod+Shift+s exec ~/.local/bin/dotfiles-screenshot region

unbindsym $mod+d
unbindsym $mod+space
bindsym $mod+space exec $menu

unbindsym $mod+b
bindsym $mod+b exec ~/.local/bin/dotfiles-open-browser

unbindsym $mod+v
bindsym $mod+v exec ~/.local/bin/dotfiles-clipboard

bindsym $mod+Tab workspace next_on_output
bindsym $mod+Shift+Tab workspace prev_on_output
bindsym Mod1+Tab workspace back_and_forth

bindsym $mod+Shift+u move scratchpad
bindsym $mod+u scratchpad show
