unbindsym $mod+$left
unbindsym $mod+$down
unbindsym $mod+$up
unbindsym $mod+$right
unbindsym $mod+Shift+$left
unbindsym $mod+Shift+$down
unbindsym $mod+Shift+$up
unbindsym $mod+Shift+$right

mode "resize" {
    unbindsym $left
    unbindsym $down
    unbindsym $up
    unbindsym $right
}

unbindsym Print
bindsym Print exec ~/.local/bin/dotfiles-screenshot full
bindsym $mod+Shift+s exec ~/.local/bin/dotfiles-screenshot region

unbindsym $mod+d
unbindsym $mod+space
bindsym $mod+space exec $menu

unbindsym $mod+b
bindsym $mod+b exec ~/.local/bin/dotfiles-open-browser

unbindsym $mod+v
bindsym $mod+v exec ~/.local/bin/dotfiles-clipboard

bindsym $mod+period exec rofimoji --selector fuzzel --selector-args='--font=Noto Emoji:size=8,JetBrainsMono Nerd Font Mono:size=8' --clipboarder wl-copy --action copy

bindsym $mod+Shift+r reload
bindsym Ctrl+Alt+Delete exec wlogout

bindsym $mod+Tab workspace next_on_output
bindsym $mod+Shift+Tab workspace prev_on_output
bindsym Mod1+Tab workspace back_and_forth

bindsym $mod+Shift+u move scratchpad
bindsym $mod+u scratchpad show

unbindsym --locked XF86AudioMute
unbindsym --locked XF86AudioLowerVolume
unbindsym --locked XF86AudioRaiseVolume
unbindsym --locked XF86AudioMicMute
bindsym --locked XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindsym --locked XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindsym --locked XF86AudioRaiseVolume exec wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
bindsym --locked XF86AudioMicMute exec wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
