for_window [window_type="dialog"] floating enable
for_window [window_type="utility"] floating enable
for_window [window_type="toolbar"] floating enable
for_window [window_type="splash"] floating enable

for_window [app_id="nm-connection-editor"] floating enable, move position center
for_window [app_id="org.pulseaudio.pavucontrol"] floating enable, move position center
